name = "akagami-net"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "akagami-research-production"
database_id = "c5d4dce7-e94e-489a-880f-36e6056f74c6"
